apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfp-lesson
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfp-lesson
  template:
    metadata:
      labels:
        app: kfp-lesson
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: kfp-lesson
          image: ghcr.io/youngseols925/kfp-lesson:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
